// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAtmaca.Infrastructure.Persistence;

#nullable disable

namespace ProjectAtmaca.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectAtmacaDbContext))]
    [Migration("20260918133447_AddTrainingPersistence")]
    partial class AddTrainingPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("AtmacaCardNumbers", "dbo")
                .HasMin(1L)
                .HasMax(999999L);

            modelBuilder.Entity("ProjectAtmaca.Application.Decisions.ApplyParticipationClassification.DecisionApplicationOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DecisionRevision")
                        .HasColumnType("int");

                    b.HasKey("OperationId");

                    b.ToTable("DecisionApplicationOperations", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.AtmacaCards.AtmacaCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("AtmacaCards", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Decisions.Decision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<int>("Effect")
                        .HasColumnType("int")
                        .HasColumnName("EffectOutcome");

                    b.Property<int>("Revision")
                        .HasColumnType("int")
                        .HasColumnName("Revision");

                    b.Property<Guid?>("SupersededByDecisionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SupersededByDecisionId");

                    b.ComplexProperty<Dictionary<string, object>>("Snapshot", "ProjectAtmaca.Domain.Decisions.Decision.Snapshot#ParticipationClassificationSnapshot", b1 =>
                        {
                            b1.Property<string>("ActivityReference")
                                .IsRequired()
                                .HasMaxLength(64)
                                .IsUnicode(false)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("SnapshotActivityReference");

                            b1.Property<Guid>("AtmacaCardId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SnapshotAtmacaCardId");

                            b1.Property<string>("Condition")
                                .HasMaxLength(32)
                                .IsUnicode(false)
                                .HasColumnType("varchar(32)")
                                .HasColumnName("SnapshotConditionCode");

                            b1.Property<DateTimeOffset?>("JoinedAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("SnapshotJoinedAt");

                            b1.Property<DateTimeOffset?>("LeftAt")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("SnapshotLeftAt");

                            b1.Property<int>("Status")
                                .HasColumnType("int")
                                .HasColumnName("SnapshotStatus");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Target", "ProjectAtmaca.Domain.Decisions.Decision.Target#DecisionTargetReference", b1 =>
                        {
                            b1.Property<Guid>("TargetId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TargetId");

                            b1.Property<int>("TargetType")
                                .HasColumnType("int")
                                .HasColumnName("TargetType");
                        });

                    b.HasKey("Id");

                    b.ToTable("Decisions", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Decisions.DecisionApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("AppliedDecisionRevision")
                        .HasColumnType("int")
                        .HasColumnName("AppliedDecisionRevision");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DecisionId");

                    b.ComplexProperty<Dictionary<string, object>>("Target", "ProjectAtmaca.Domain.Decisions.DecisionApplication.Target#DecisionTargetReference", b1 =>
                        {
                            b1.Property<Guid>("TargetId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("TargetId");

                            b1.Property<int>("TargetType")
                                .HasColumnType("int")
                                .HasColumnName("TargetType");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DecisionId", "AppliedAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_DecisionApplications_Decision_AppliedAt_Id");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DecisionId", "AppliedAtUtc", "Id"), new[] { "AppliedDecisionRevision" });

                    b.ToTable("DecisionApplications", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Participations.Participation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ActivityReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ActivityReference");

                    b.Property<Guid>("AtmacaCardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AtmacaCardId");

                    b.Property<string>("Condition")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("ConditionCode");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CreatedBy");

                    b.Property<Guid?>("CreatedByActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedByActorId");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("JoinedAt");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedAtUtc");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LastModifiedBy");

                    b.Property<Guid?>("LastModifiedByActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifiedByActorId");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LeftAt");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Note");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("ActivityReference")
                        .HasDatabaseName("IX_Participations_ActivityReference");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ActivityReference"), new[] { "AtmacaCardId", "Status", "Condition", "JoinedAt", "LeftAt" });

                    b.HasIndex("AtmacaCardId", "ActivityReference")
                        .IsUnique()
                        .HasDatabaseName("UX_Participations_AtmacaCard_Activity");

                    b.HasIndex("AtmacaCardId", "CreatedAtUtc", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("IX_Participations_AtmacaCard_CreatedAt_Id");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AtmacaCardId", "CreatedAtUtc", "Id"), new[] { "ActivityReference", "Status", "Condition", "JoinedAt", "LeftAt" });

                    b.ToTable("Participations", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Persons.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BloodType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotherName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PrimaryPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Persons.PersonCitizenship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("AcquiredOn")
                        .HasColumnType("date");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonCitizenships", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Persons.Registration.PersonRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NationalIdentityNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PassportMatchKey")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NationalIdentityNumber")
                        .IsUnique()
                        .HasFilter("[NationalIdentityNumber] IS NOT NULL");

                    b.HasIndex("PassportMatchKey");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("PersonRegistrations", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Trainings.Training", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedByActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SeasonOrganization")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("nvarchar(73)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Trainings", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Infrastructure.Persistence.Persons.PersonRegistrationOperation", b =>
                {
                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActorId", "OperationId");

                    b.HasIndex("CardId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonRegistrationOperations", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Infrastructure.Persistence.Security.ActorIdentityMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("IssuerByteLength")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATALENGTH([Issuer])", true);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("SubjectByteLength")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATALENGTH([Subject])", true);

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("Issuer", "IssuerByteLength", "Subject", "SubjectByteLength")
                        .IsUnique();

                    b.ToTable("ActorIdentityMappings", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Infrastructure.Persistence.Security.ActorPermissionGrant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("PermissionCodeByteLength")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("DATALENGTH([PermissionCode])", true);

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "PermissionCode", "PermissionCodeByteLength")
                        .IsUnique();

                    b.ToTable("ActorPermissionGrants", (string)null);
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.AtmacaCards.AtmacaCard", b =>
                {
                    b.HasOne("ProjectAtmaca.Domain.Persons.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Persons.PersonCitizenship", b =>
                {
                    b.HasOne("ProjectAtmaca.Domain.Persons.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectAtmaca.Domain.Persons.Registration.PersonRegistration", b =>
                {
                    b.HasOne("ProjectAtmaca.Domain.Persons.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectAtmaca.Infrastructure.Persistence.Persons.PersonRegistrationOperation", b =>
                {
                    b.HasOne("ProjectAtmaca.Domain.AtmacaCards.AtmacaCard", null)
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectAtmaca.Domain.Persons.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
