// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAtmaca.Infrastructure.Persistence;

#nullable disable

namespace ProjectAtmaca.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectAtmacaDbContext))]
    partial class ProjectAtmacaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectAtmaca.Domain.Participations.Participation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("ActivityReference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ActivityReference");

                    b.Property<Guid>("AtmacaCardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AtmacaCardId");

                    b.Property<string>("Condition")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("ConditionCode");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTimeOffset?>("JoinedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("JoinedAt");

                    b.Property<DateTime?>("LastModifiedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedAtUtc");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LastModifiedBy");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LeftAt");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("Note");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("AtmacaCardId", "ActivityReference")
                        .IsUnique()
                        .HasDatabaseName("UX_Participations_AtmacaCard_Activity");

                    b.ToTable("Participations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
